Repository RooCodeInc/Roo-Code-Docs, pull requests merged in 2025-02, with the labels that each got.

#55 Update provider titles
  docs/providers/anthropic.md
  docs/providers/bedrock.md
  docs/providers/deepseek.md
  docs/providers/gemini.md
  docs/providers/glama.md
  docs/providers/lmstudio.md
  docs/providers/mistral.md
  docs/providers/ollama.md
  docs/providers/openai-compatible.md
  docs/providers/openai.md
  docs/providers/openrouter.md
  docs/providers/requesty.md
  docs/providers/unbound.md
  docs/providers/vertex.md
  docs/providers/vscode-lm.md
Labels: documentation, size:M

#56 Update mistral.md
  docs/providers/mistral.md
Labels: documentation, size:M, lgtm

#57 Update community.md
  docs/community.md
Labels: documentation, enhancement, size:M, lgtm

#58 Debug mode and power steering
  docs/advanced-usage/custom-modes.md
  docs/advanced-usage/experimental-features.md
  docs/advanced-usage/model-temperature.md
  docs/advanced-usage/prompt-engineering.md
  docs/basic-usage/modes.md
  docs/faq.md
  docs/index.md
Labels: documentation, size:S

#59 Dedupe local model instructions
  docs/advanced-usage/local-models.md
Labels: documentation, size:L

#62 Update community.md
  docs/community.md
Labels: documentation, size:XS, lgtm
