Repository RooCodeInc/Roo-Code-Docs, pull requests merged in 2025-04, with the labels that each got.

#109 Cleanup now that we're using Vercel
  .github/workflows/pages.yml
  docusaurus.config.ts
  static/.nojekyll
Labels: size:M

#110 Add Os-specific MCP configuration example to documentation
  docs/features/mcp/using-mcp-in-roo.md
Labels: documentation, size:M, lgtm

#112 Update experimental-features.md
  docs/features/experimental/experimental-features.md
  docs/features/fast-edits.md
  docs/features/tools/apply-diff.md
  static/img/fast-edits/fast-edits-2.png
Labels: documentation, size:L

#114 Read file update
  docs/features/tools/read-file.md
  sidebars.ts
Labels: documentation, size:M

#117 Add release notes for versions 3.11.5, 3.11.6, and 3.11.7 and update …
  docs/update-notes/index.md
  docs/update-notes/v3.11.5.md
  docs/update-notes/v3.11.6.md
  docs/update-notes/v3.11.7.md
  sidebars.ts
Labels: documentation, size:M

#118 Add release notes for version 3.11.8 and update sidebar configuration
  docs/update-notes/index.md
  docs/update-notes/v3.11.8.md
  sidebars.ts
Labels: size:S

#119 Update docs to reflect change to .roorules
  docs/faq.md
  docs/features/custom-instructions.md
  docs/features/custom-modes.md
Labels: documentation, size:S

#115 Add Roo Commander project to community page
  docs/community.md
Labels: documentation, size:XS, lgtm

#121 docs: clarify folder mention format and description in context mentions
  docs/basic-usage/context-mentions.md
Labels: size:S

#122 Enhance documentation and update release notes for Roo Code
  .roomodes
  docs/advanced-usage/rate-limits-costs.md
  docs/features/api-configuration-profiles.md
  docs/features/boomerang-tasks.md
  docs/features/boomerang-tasks.mdx
  docs/features/browser-use.md
  docs/features/browser-use.mdx
  docs/features/custom-instructions.md
  docs/features/custom-modes.md
  docs/features/mcp/using-mcp-in-roo.md
  docs/features/tools/read-file.md
  docs/update-notes/index.md
  docs/update-notes/v2.1.10.md
  docs/update-notes/v2.1.16.md
  docs/update-notes/v2.1.19.md
  docs/update-notes/v2.1.21.md
  docs/update-notes/v2.1.3.md
  docs/update-notes/v2.1.4.md
  docs/update-notes/v2.1.6.md
  docs/update-notes/v2.1.8.md
  docs/update-notes/v2.1.9.md
  docs/update-notes/v2.2.11.md
  docs/update-notes/v2.2.12.md
  docs/update-notes/v2.2.17.md
  docs/update-notes/v2.2.2.md
  docs/update-notes/v2.2.20.md
  docs/update-notes/v2.2.21.md
  docs/update-notes/v2.2.26.md
  docs/update-notes/v2.2.27.md
  docs/update-notes/v2.2.28.md
  docs/update-notes/v2.2.29.md
  docs/update-notes/v2.2.3.md
  docs/update-notes/v2.2.31.md
  docs/update-notes/v2.2.32.md
  docs/update-notes/v2.2.35.md
  docs/update-notes/v2.2.36.md
  docs/update-notes/v2.2.38.md
  docs/update-notes/v2.2.39.md
  docs/update-notes/v2.2.4.md
  docs/update-notes/v2.2.41.md
  docs/update-notes/v2.2.42.md
  docs/update-notes/v2.2.43.md
  docs/update-notes/v2.2.44.md
  docs/update-notes/v2.2.5.md
  docs/update-notes/v3.11.1.md
  docs/update-notes/v3.11.10.md
  docs/update-notes/v3.11.2.md
  docs/update-notes/v3.11.3.md
  docs/update-notes/v3.11.5.md
  docs/update-notes/v3.11.7.md
  docs/update-notes/v3.11.8.md
  docs/update-notes/v3.11.9.md
  docs/update-notes/v3.11.md
  docs/update-notes/v3.3.26.md
  sidebars.ts
  static/img/api-configuration-profiles/api-configuration-profiles-12.png
Labels: documentation, size:L

#123 docs: enhance custom instructions and modes documentation with file s…
  docs/features/custom-instructions.md
  docs/features/custom-modes.md
Labels: size:M

#124 docs: enhance custom modes documentation with model persistence details
  docs/basic-usage/using-modes.md
  docs/features/custom-modes.md
Labels: size:XS

#126 3.11.13
  docs/community.md
  docs/faq.md
  docs/features/custom-modes.md
  docs/features/shell-integration.md
  docs/troubleshooting/shell-integration.md
  docs/update-notes/index.md
  docs/update-notes/v3.11.11.md
  docs/update-notes/v3.11.12.md
  docs/update-notes/v3.11.13.md
  docs/update-notes/v3.11.8.md
  docs/update-notes/v3.11.md
  docusaurus.config.ts
  sidebars.ts
  static/img/shell-integration/shell-integration-1.png
  static/img/shell-integration/shell-integration-2.png
  static/img/shell-integration/shell-integration-3.png
  static/img/shell-integration/shell-integration-4.png
  static/img/shell-integration/shell-integration-5.png
  static/img/shell-integration/shell-integration-6.png
  static/img/shell-integration/shell-integration-7.png
  static/img/shell-integration/shell-integration.png
  static/img/v3.11.13/v3.11.13-1.png
  static/img/v3.11.13/v3.11.13.png
Labels: documentation, size:XL

#128 docs: enhance terminal output limit description for clarity and token…
  docs/features/shell-integration.md
Labels: documentation, size:XS

#129 Changed your-first-task image to include new roo icon
  .gitignore
  static/img/your-first-task/your-first-task.png
Labels: documentation, size:XS, lgtm

#130 docs: improve shell integration troubleshooting guidance
  docs/features/shell-integration.md
Labels: documentation, size:L, lgtm

#131 docs: update browser use documentation to clarify model support requi…
  docs/features/browser-use.mdx
Labels: size:XS

#132 Update notes 3.11.17
  .roomodes
  docs/update-notes/index.md
  docs/update-notes/v3.11.14.md
  docs/update-notes/v3.11.15.md
  docs/update-notes/v3.11.16.md
  docs/update-notes/v3.11.17.md
  sidebars.ts
Labels: documentation, size:M

#133 Update the social share image
  docusaurus.config.ts
  static/img/social-share.png
Labels: size:XS, lgtm

#134 Misc
  docs/basic-usage/context-mentions.md
  docs/features/footgun-prompting.md
  docs/getting-started/connecting-api-provider.md
  docs/getting-started/installing.mdx
Labels: size:M

#135 Update icon
  .vscode/settings.json
  docs/basic-usage/the-chat-interface.md
  docs/faq.md
  docs/features/model-temperature.md
  docs/getting-started/connecting-api-provider.md
  docs/getting-started/installing.mdx
  docs/getting-started/your-first-task.md
  docs/providers/ollama.md
  src/components/KangarooIcon.tsx
  static/img/installing/installing-3.png
Labels: size:M

#137 Update sidebar label for API provider documentation
  docs/getting-started/connecting-api-provider.md
Labels: documentation, size:XS, lgtm

#136 Add docs for xai
  docs/providers/xai.md
  sidebars.ts
Labels: documentation, size:M, lgtm

#139 docs: add keyboard shortcuts documentation and v3.12.x release notes
  docs/features/api-configuration-profiles.md
  docs/features/keyboard-shortcuts.md
  docs/features/suggested-responses.md
  docs/tips-and-tricks.md
  docs/update-notes/index.md
  docs/update-notes/v3.12.0.md
  docs/update-notes/v3.12.1.md
  docs/update-notes/v3.12.2.md
  sidebars.ts
Labels: documentation, size:L

#140 docs: enhance custom modes documentation with overriding instructions…
  docs/features/custom-modes.md
Labels: size:M

#142 3.13
  docs/basic-usage/using-modes.md
  docs/features/custom-modes.md
  docs/features/tools/append-to-file.md
  docs/tips-and-tricks.md
  docs/update-notes/index.md
  docs/update-notes/v3.13.0.md
  docs/update-notes/v3.13.1.md
  sidebars.ts
Labels: size:L

#143 docs: update model names in sticky models section for clarity
  docs/basic-usage/using-modes.md
Labels: size:XS

#144 docs: correct terminology from 'tasks' to 'modes' in sticky models se…
  docs/basic-usage/using-modes.md
Labels: size:XS

#145 docs: improve clarity and formatting in Boomerang Tasks documentation
  docs/features/boomerang-tasks.mdx
Labels: size:S

#146 Implement code changes to enhance functionality and improve performance
  static/img/how-tools-work/how-tools-work.png
Labels: size:XS

#147 docs: Update Vertex AI provider auth methods
  docs/providers/vertex.md
Labels: documentation, size:S, lgtm

#148 docs: add context variables section to the footgun page
  docs/features/footgun-prompting.md
Labels: documentation, size:M

#138 docs: Add Documentation of Shell Integration for Cygwin + Fish Setup
  docs/features/shell-integration.md
  static/img/shell-integration/shell-integration-8.png
Labels: documentation, size:M, lgtm

#151 3.14 Part A
  docs/features/footgun-prompting.md
  docs/features/tools/append-to-file.md
  docs/features/tools/apply-diff.md
  docs/features/tools/insert-content.md
  docs/features/tools/list-files.md
  docs/features/tools/search-and-replace.md
  docs/features/tools/tool-use-overview.md
  docs/features/tools/write-to-file.md
  docs/update-notes/index.md
  docs/update-notes/v3.13.0.md
  docs/update-notes/v3.13.2.md
  docs/update-notes/v3.14.0.md
  docs/update-notes/v3.14.1.md
  sidebars.ts
  static/img/footgun-prompting/footgun-prompting-1.png
  static/img/v3.14.0/v3.14.0.png
Labels: size:L

#153 docs: Fix typo in terminal improvements section of v3.14.2 release notes
  docs/update-notes/v3.14.2.md
Labels: size:XS

#155 docs: Update prompt caching description for Gemini models in release …
  docs/update-notes/v3.14.2.md
  docs/update-notes/v3.14.md
Labels: size:XS

#156 Added SPARC
  docs/community.md
Labels: documentation, size:S

#157 docs: Update using modes and boomerang tasks documentation to include…
  docs/basic-usage/using-modes.md
  docs/features/boomerang-tasks.mdx
  docs/features/custom-modes.md
Labels: size:L

#158 3.14.3b
  docs/update-notes/index.md
  docs/update-notes/v3.14.3.md
  docs/update-notes/v3.14.md
  sidebars.ts
  static/img/v3.14.3/v3.14.3-1.png
  static/img/v3.14.3/v3.14.3.png
Labels: size:M

#160 Update the-chat-interface.md
  docs/basic-usage/the-chat-interface.md
Labels: documentation, size:XS, lgtm

#159 added Research Mode and fixed h2 title for SPARC
  docs/community.md
Labels: documentation, size:S, lgtm

#162 Prompt construction
  docs/advanced-usage/available-tools/access-mcp-resource.md
  docs/advanced-usage/available-tools/apply-diff.md
  docs/advanced-usage/available-tools/ask-followup-question.md
  docs/advanced-usage/available-tools/attempt-completion.md
  docs/advanced-usage/available-tools/browser-action.md
  docs/advanced-usage/available-tools/execute-command.md
  docs/advanced-usage/available-tools/insert-content.md
  docs/advanced-usage/available-tools/list-code-definition-names.md
  docs/advanced-usage/available-tools/list-files.md
  docs/advanced-usage/available-tools/new-task.md
  docs/advanced-usage/available-tools/read-file.md
  docs/advanced-usage/available-tools/search-and-replace.md
  docs/advanced-usage/available-tools/search-files.md
  docs/advanced-usage/available-tools/switch-mode.md
  docs/advanced-usage/available-tools/tool-use-overview.md
  docs/advanced-usage/available-tools/use-mcp-tool.md
  docs/advanced-usage/available-tools/write-to-file.md
  docs/advanced-usage/prompt-structure.md
  docs/basic-usage/how-tools-work.md
  docs/basic-usage/using-modes.md
  docs/features/boomerang-tasks.mdx
  docs/features/experimental/experimental-features.md
  docs/features/fast-edits.md
  docs/features/shell-integration.md
  docs/features/suggested-responses.md
  docs/index.md
  docs/update-notes/v3.11.md
  docs/update-notes/v3.14.0.md
  docs/update-notes/v3.14.3.md
  docs/update-notes/v3.14.md
  docusaurus.config.ts
  sidebars.ts
Labels: documentation, size:L

#163 docs: Add optional base URL instruction for OpenAI API setup
  docs/providers/openai.md
Labels: documentation, size:XS, lgtm

#165 3.15
  .roomodes
  docs/update-notes/index.md
  docs/update-notes/v3.15.md
  sidebars.ts
Labels: size:M
