Repository RooCodeInc/Roo-Code-Docs, pull requests merged in 2025-05, with the labels that each got.

#167 docs: Update connecting-api-provider.md
  docs/getting-started/connecting-api-provider.md
Labels: documentation, size:XS

#169 3.15.2
  .roomodes
  docs/features/custom-modes.md
  docs/update-notes/index.md
  docs/update-notes/v3.15.2.md
  docs/update-notes/v3.15.md
  sidebars.ts
  static/img/v3.15.2/v3.15.2.png
Labels: documentation, size:M

#170 docs: Update release notes for versions 3.15.3, 3.15.4, and 3.15.5; a…
  docs/update-notes/index.md
  docs/update-notes/v3.15.3.md
  docs/update-notes/v3.15.4.md
  docs/update-notes/v3.15.5.md
  docs/update-notes/v3.15.md
  sidebars.ts
Labels: documentation, size:M

#172 docs: Add context poisoning section to advanced usage documentation
  docs/advanced-usage/context-poisoning.md
  sidebars.ts
Labels: documentation, size:M

#175 docs: Add contributing guide to sidebar navigation
  docs/contributing.md
  sidebars.ts
Labels: documentation, size:L

#176 docs: Update contribution guidelines for issue creation and feature p…
  docs/contributing.md
  sidebars.ts
Labels: documentation, size:L

#173 docs: Add Maestro Project to community showcase
  docs/community/index.md
  docs/community/maestro.md
Labels: documentation, size:S

#177 MCP - Context7
  docs/features/mcp/overview.md
  docs/features/mcp/recommended-mcp-servers.md
  sidebars.ts
  static/img/recommended-mcp-servers/context7-global-setup.png
  static/img/recommended-mcp-servers/context7-project-setup.PNG
  static/img/recommended-mcp-servers/context7-running.PNG
Labels: documentation, size:L

#179 Litellm
  docs/providers/litellm.md
  sidebars.ts
  static/img/litellm/litellm.png
Labels: documentation, size:M, lgtm

#180 Fixed Embedding Issues.
  docs/features/mcp/recommended-mcp-servers.md
  static/img/recommended-mcp-servers/context7-global-setup-fixed.png
  static/img/recommended-mcp-servers/context7-project-setup-fixed.png
  static/img/recommended-mcp-servers/context7-running-fixed.png
Labels: bug, size:XS, lgtm

#181 docs: Update release notes for versions 3.16.1, 3.16.2, and 3.16.3; a…
  docs/update-notes/index.md
  docs/update-notes/v3.16.1.md
  docs/update-notes/v3.16.2.md
  docs/update-notes/v3.16.3.md
  docs/update-notes/v3.16.md
  sidebars.ts
Labels: documentation, size:L

#182 Fix sidebar Maestro
  sidebars.ts
Labels: bug, size:XS

#183 docs: Enhance MCP server documentation with detailed creation process…
  docs/advanced-usage/available-tools/tool-use-overview.md
  docs/features/mcp/using-mcp-in-roo.md
Labels: documentation, size:M

#184 docs: Update custom modes documentation and add new interface image
  docs/features/custom-modes.md
  static/img/custom-modes/custom-modes-1.png
Labels: documentation, size:L
