Repository RooCodeInc/Roo-Code-Docs, pull requests merged in 2025-03, with the labels that each got.

#63 Update community.md
  docs/community.md
Labels: documentation, size:XS, lgtm

#67 Add docs for configuration profiles
  docs/advanced-usage/api-configuration-profiles.md
  docs/advanced-usage/model-temperature.md
  sidebars.ts
Labels: documentation, size:M

#68 feat: add shell integration guide
  docs/faq.md
  docs/troubleshooting/shell-integration.md
  sidebars.ts
Labels: documentation, size:L, lgtm

#69 Add tips & tricks page
  docs/tips-and-tricks.md
  sidebars.ts
Labels: documentation, size:S

#73 Tweaked doc writing mode and workspace settings
  .roomodes
  .vscode/settings.json
Labels: documentation, size:S, lgtm

#71 Improve references to LLM providers and routers in documentation
  docs/advanced-usage/large-projects.md
  docs/faq.md
  docs/getting-started/connecting-api-provider.md
  docs/providers/anthropic.md
  docs/providers/requesty.md
Labels: documentation, size:M, lgtm

#76 Update connecting-api-provider.md
  docs/getting-started/connecting-api-provider.md
Labels: documentation, size:S, lgtm

#79 Basic use sections update
  .clinerules
  .gitignore
  .roomodes
  docs/advanced-usage/tool-reference.md
  docs/basic-usage/context-mentions.md
  docs/basic-usage/how-tools-work.md
  docs/basic-usage/modes.md
  docs/basic-usage/the-chat-interface.md
  docs/basic-usage/typing-your-requests.md
  docs/basic-usage/using-modes.md
  docs/basic-usage/using-tools.md
  docs/faq.md
  docs/index.md
  sidebars.ts
  src/css/custom.css
  static/img/available-tools/available-tools.png
  static/img/context-mentions/context-mentions-1.png
  static/img/context-mentions/context-mentions-2.png
  static/img/context-mentions/context-mentions-3.png
  static/img/context-mentions/context-mentions-4.png
  static/img/context-mentions/context-mentions-5.png
  static/img/context-mentions/context-mentions-6.png
  static/img/context-mentions/context-mentions.png
  static/img/modes/modes-1.png
  static/img/modes/modes-2.png
  static/img/modes/modes.png
  static/img/the-chat-interface/the-chat-interface-1.png
  static/img/typing-your-requests/typing-your-requests.png
Labels: documentation, size:XL, lgtm

#80 Update your-first-task.md
  docs/getting-started/your-first-task.md
Labels: documentation, size:XS

#81 Advanced usage refactor: Stage 1
  docs/advanced-usage/api-configuration-profiles.md
  docs/advanced-usage/custom-instructions.md
  docs/advanced-usage/custom-modes.md
  static/img/api-configuration-profiles/api-configuration-profiles-1.png
  static/img/api-configuration-profiles/api-configuration-profiles-10.png
  static/img/api-configuration-profiles/api-configuration-profiles-11.png
  static/img/api-configuration-profiles/api-configuration-profiles-2.png
  static/img/api-configuration-profiles/api-configuration-profiles-3.png
  static/img/api-configuration-profiles/api-configuration-profiles-5.png
  static/img/api-configuration-profiles/api-configuration-profiles-7.png
  static/img/api-configuration-profiles/api-configuration-profiles-8.png
  static/img/api-configuration-profiles/api-configuration-profiles-9.png
  static/img/api-configuration-profiles/api-configuration-profiles.png
  static/img/custom-instructions/custom-instructions-2.png
  static/img/custom-instructions/custom-instructions.png
  static/img/custom-modes/custom-modes-1.png
  static/img/custom-modes/custom-modes-2.png
  static/img/custom-modes/custom-modes.png
Labels: documentation, size:L, lgtm

#82 Enhance checkpoints documentation: detail functionality, images
  docs/advanced-usage/checkpoints.md
  static/img/checkpoints/checkpoints-1.png
  static/img/checkpoints/checkpoints-2.png
  static/img/checkpoints/checkpoints-3.png
  static/img/checkpoints/checkpoints-4.png
  static/img/checkpoints/checkpoints-6.png
  static/img/checkpoints/checkpoints-7.png
  static/img/checkpoints/checkpoints-9.png
  static/img/checkpoints/checkpoints.png
Labels: documentation, size:L, lgtm

#84 Add MCP documentation and images for enhanced guidance
  docs/advanced-usage/mcp.md
  docs/mcp/mcp-vs-api.md
  docs/mcp/overview.md
  docs/mcp/server-transports.md
  docs/mcp/using-mcp-in-roo.md
  docs/mcp/what-is-mcp.md
  sidebars.ts
  static/img/using-mcp-in-roo/using-mcp-in-roo-1.png
  static/img/using-mcp-in-roo/using-mcp-in-roo-2.png
  static/img/using-mcp-in-roo/using-mcp-in-roo-3.png
  static/img/using-mcp-in-roo/using-mcp-in-roo-4.png
  static/img/using-mcp-in-roo/using-mcp-in-roo-5.png
  static/img/using-mcp-in-roo/using-mcp-in-roo-6.png
  static/img/using-mcp-in-roo/using-mcp-in-roo-7.png
  static/img/using-mcp-in-roo/using-mcp-in-roo-8.png
  static/img/using-mcp-in-roo/using-mcp-in-roo.png
Labels: documentation, size:XL, lgtm

#85 Update using-mcp-in-roo.md
  docs/mcp/using-mcp-in-roo.md
Labels: documentation, size:XS, lgtm

#87 Changed layout of menu and sections
  .roomodes
  docs/advanced-usage/local-models.md
  docs/advanced-usage/mcp.md
  docs/advanced-usage/prompt-engineering.md
  docs/advanced-usage/rate-limits-costs.md
  docs/basic-usage/how-tools-work.md
  docs/basic-usage/typing-your-requests.md
  docs/basic-usage/using-modes.md
  docs/community.md
  docs/faq.md
  docs/features/api-configuration-profiles.md
  docs/features/auto-approving-actions.md
  docs/features/checkpoints.md
  docs/features/code-actions.md
  docs/features/custom-instructions.md
  docs/features/custom-modes.md
  docs/features/enhance-prompt.md
  docs/features/experimental/experimental-features.md
  docs/features/mcp/mcp-vs-api.md
  docs/features/mcp/overview.md
  docs/features/mcp/server-transports.md
  docs/features/mcp/using-mcp-in-roo.md
  docs/features/mcp/what-is-mcp.md
  docs/features/model-temperature.md
  docs/features/tool-reference.md
  docs/getting-started/your-first-task.md
  docs/index.md
  docs/mcp/overview.md
  docs/providers/mistral.md
  docs/providers/openai-compatible.md
  docs/providers/openai.md
  docs/tips-and-tricks.md
  docusaurus.config.ts
  package-lock.json
  package.json
  sidebars.ts
Labels: documentation, size:L, lgtm

#91 Update logo
  .gitignore
  docusaurus.config.ts
  static/img/favicon.ico
  static/img/roo-code-logo-dark.png
  static/img/roo-code-logo-white.png
Labels: size:XS

#90 Update documentation with new features and available model info
  docs/community.md
  docs/features/experimental/experimental-features.md
  docs/features/more-features.md
  docs/providers/anthropic.md
  docs/providers/gemini.md
  docs/providers/vscode-lm.md
  docs/tips-and-tricks.md
  sidebars.ts
Labels: documentation, size:M, lgtm

#93 Update social share image
  docusaurus.config.ts
  static/img/roo-code-logo-white-stacked.png
Labels: size:XS

#95 Boomerang tasks
  docs/features/boomerang-tasks.md
  sidebars.ts
Labels: documentation, size:M

#98 Add Posthog
  .env.example
  .github/workflows/docusaurus-build.yml
  .github/workflows/pages.yml
  .gitignore
  docusaurus.config.ts
  package-lock.json
  package.json
Labels: size:M, lgtm

#97 Enhanced Orchestrator Mode with Advanced Task Management by @iiwish
  docs/community.md
Labels: enhancement, size:S, lgtm

#100 Update Boomerang Tasks documentation with configuration download and …
  docs/features/boomerang-tasks.md
Labels: documentation, size:S, lgtm

#101 Updated Docs for Various Providers
  .gitignore
  docs/features/more-features.md
  docs/providers/anthropic.md
  docs/providers/bedrock.md
  docs/providers/gemini.md
  docs/providers/human-relay.md
  docs/providers/mistral.md
  docs/providers/openai-compatible.md
  docs/providers/openai.md
  docs/providers/vertex.md
  sidebars.ts
Labels: documentation, size:L

#102 Fix image reference in custom modes documentation missing image
  docs/features/custom-modes.md
Labels: documentation, size:XS, lgtm

#103 Remove checkpoints section from experimental features documentation
  docs/features/experimental/experimental-features.md
Labels: size:XS, lgtm

#104 Add Footgun Prompting feature documentation and sidebar entry
  docs/features/footgun-prompting.md
  sidebars.ts
  static/img/footgun-prompting/footgun-prompting.png
Labels: documentation, size:M, lgtm

#105 Add Fast Edits feature documentation and sidebar entry
  docs/features/fast-edits.md
  sidebars.ts
  static/img/fast-edits/fast-edits.png
Labels: documentation, size:M, lgtm

#106 Add a link to report an issue
  docusaurus.config.ts
  src/components/ReportIssue/index.js
  src/components/ReportIssue/styles.module.css
  src/constants.ts
  src/theme/DocItem/index.js
Labels: enhancement, size:L, lgtm

#107 Update custom-modes.md with .roomodes
  docs/features/custom-modes.md
Labels: documentation, size:XS, lgtm
